tasks:
  - init: yarn
    command: yarn start
ports:
  - name: Web
    port: 3000
    onOpen: ignore # create-react-app opens browser automatically
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
