const Card = (img, type, name, cost) => ({ 
  id: parseInt(img.substring(5, 9), 10),
  type,
  name,
  cost, 
  img
})

export const allCards = [
  Card("Card_0001_bake.png", "Debuff", "Big Head", 2),
  Card("Card_0010_bake.png", "Weapon", "Albatross 21", 3),
  Card("Card_0019_bake.png", "Buff", "Silent Steps", 1),
  Card("Card_0028_bake.png", "Buff", "Vampire Bullets", 3),
  Card("Card_0038_bake.png", "Buff", "Tin Man", 4),
  Card("Card_0051_bake.png", "Buff", "Card Profaner", 4),
  Card("Card_0064_bake.png", "Companion", "Sticky Bomb", 1),
  Card("Card_0078_bake.png", "Buff", "Lottery Ticket", 2),
  Card("Card_0096_bake.png", "Buff", "Bigger Explosions", 1),
  Card("Card_0114_bake.png", "Debuff", "Pixel Vision", 1),
  Card("Card_1005_bake.png", "Personality", "Classic", 2),
  Card("Card_0002_bake.png", "Buff", "Small Head", 1),
  Card("Card_0011_bake.png", "Debuff", "Less Accuracy", 1),
  Card("Card_0020_bake.png", "Weapon", "Brass Hopper", 1),
  Card("Card_0030_bake.png", "Buff", "Energy Drink", 1),
  Card("Card_0041_bake.png", "Companion", "Wall", 1),
  Card("Card_0056_bake.png", "Buff", "Card Thief", 4),
  Card("Card_0067_bake.png", "Weapon", "Punch-R", 3),
  Card("Card_0083_bake.png", "Wild", "Hot Potato", 2),
  Card("Card_0098_bake.png", "Buff", "Thick Skin", 1),
  Card("Card_0124_bake.png", "Companion", "Dr. MoleBOT", 1),
  Card("Card_1006_bake.png", "Personality", "Thick Coat", 2),
  Card("Card_0003_bake.png", "Debuff", "Health Down", 2),
  Card("Card_0012_bake.png", "Buff", "More Accuracy", 1),
  Card("Card_0021_bake.png", "Weapon", "Laika", 2),
  Card("Card_0031_bake.png", "Buff", "Helmet", 2),
  Card("Card_0042_bake.png", "Companion", "Bomb Belt", 2),
  Card("Card_0057_bake.png", "Companion", "Land Mine", 1),
  Card("Card_0068_bake.png", "Companion", "Toxic Bomb", 2),
  Card("Card_0085_bake.png", "Buff", "Bomb Lover", 3),
  Card("Card_0099_bake.png", "Buff", "Berserker", 2),
  Card("Card_0127_bake.png", "Buff", "Pyromania", 1),
  Card("Card_1007_bake.png", "Personality", "Power Legs", 2),
  Card("Card_0004_bake.png", "Buff", "Health Up", 2),
  Card("Card_0013_bake.png", "Debuff", "Rubber Bullets", 2),
  Card("Card_0022_bake.png", "Buff", "Medkit", 2),
  Card("Card_0032_bake.png", "Weapon", "Akimbo", 3),
  Card("Card_0044_bake.png", "Debuff", "Garbage Day", 1),
  Card("Card_0058_bake.png", "Companion", "Bear Trap", 1),
  Card("Card_0069_bake.png", "Weapon", "Katana", 3),
  Card("Card_0086_bake.png", "Debuff", "Frozen Gun", 2),
  Card("Card_0100_bake.png", "Trap", "Ninja Log", 2),
  Card("Card_0128_bake.png", "Wild", "Warp Room", 1),
  Card("Card_1010_bake.png", "Personality", "Runner", 2),
  Card("Card_0005_bake.png", "Debuff", "Move Slower", 2),
  Card("Card_0014_bake.png", "Buff", "Steel Bullets", 2),
  Card("Card_0023_bake.png", "Debuff", "Invisible Health", 1),
  Card("Card_0033_bake.png", "Companion", "CA-Turret", 2),
  Card("Card_0046_bake.png", "Companion", "Ice Block", 1),
  Card("Card_0059_bake.png", "Buff", "Invisible", 3),
  Card("Card_0070_bake.png", "Debuff", "Swap Weapons", 3),
  Card("Card_0088_bake.png", "Companion", "Kaboomber", 2),
  Card("Card_0102_bake.png", "Trap", "Self-destruct Device", 3),
  Card("Card_0137_bake.png", "Companion", "Teleport Bomb", 1),
  Card("Card_1011_bake.png", "Personality", "Katana Lover", 2),
  Card("Card_0006_bake.png", "Buff", "Move Faster", 1),
  Card("Card_0015_bake.png", "Debuff", "Small Mag", 2),
  Card("Card_0024_bake.png", "Debuff", "Invisible Hand", 3),
  Card("Card_0034_bake.png", "Wild", "Titan", 4),
  Card("Card_0047_bake.png", "Companion", "Bouncy Wall", 2),
  Card("Card_0060_bake.png", "Debuff", "Mind Blowing", 4),
  Card("Card_0071_bake.png", "Buff", "Predator Vision", 1),
  Card("Card_0090_bake.png", "Trap", "Counter Card", 3),
  Card("Card_0104_bake.png", "Companion", "Karratov", 2),
  Card("Card_1001_bake.png", "Personality", "It's Medicinal", 2),
  Card("Card_1013_bake.png", "Personality", "Big Bullets", 2),
  Card("Card_0007_bake.png", "Buff", "Double Jump", 1),
  Card("Card_0016_bake.png", "Buff", "Big Mag", 2),
  Card("Card_0025_bake.png", "Weapon", "FK-82", 3),
  Card("Card_0035_bake.png", "Debuff", "Disarm", 2),
  Card("Card_0048_bake.png", "Companion", "Smoke Bomb", 1),
  Card("Card_0061_bake.png", "Wild", "Heartless", 3),
  Card("Card_0072_bake.png", "Buff", "Phantom Bullets", 3),
  Card("Card_0091_bake.png", "Trap", "Mirror Card", 2),
  Card("Card_0109_bake.png", "Wild", "Parlay", 3),
  Card("Card_1002_bake.png", "Personality", "Brasslover", 1),
  Card("Card_1014_bake.png", "Personality", "Dither & Banding", 2),
  Card("Card_0008_bake.png", "Debuff", "No Jump", 2),
  Card("Card_0017_bake.png", "Debuff", "Slow Reload", 2),
  Card("Card_0026_bake.png", "Buff", "Bullet Time", 1),
  Card("Card_0036_bake.png", "Buff", "Poison Bullets", 2),
  Card("Card_0049_bake.png", "Companion", "Flash Bomb", 1),
  Card("Card_0062_bake.png", "Wild", "Nuke", 2),
  Card("Card_0074_bake.png", "Debuff", "Clown Shoes", 1),
  Card("Card_0092_bake.png", "Buff", "Love Letter", 1),
  Card("Card_0111_bake.png", "Debuff", "Barbed Cards", 2),
  Card("Card_1003_bake.png", "Personality", "Reading Glasses", 2),
  Card("Card_0009_bake.png", "Weapon", "Boomstick", 3),
  Card("Card_0018_bake.png", "Buff", "Quick Reload", 2),
  Card("Card_0027_bake.png", "Debuff", "Poison", 1),
  Card("Card_0037_bake.png", "Companion", "Bomb", 1),
  Card("Card_0050_bake.png", "Buff", "Extra Cards", 3),
  Card("Card_0063_bake.png", "Weapon", "Golden Boira", 2),
  Card("Card_0075_bake.png", "Debuff", "Empty Mag", 2),
  Card("Card_0094_bake.png", "Buff", "Ninja Smoke", 1),
  Card("Card_0113_bake.png", "Buff", "Painkillers", 3),
  Card("Card_1004_bake.png", "Personality", "Badass", 2),
].sort((a, b) => a.id - b.id)

export const cards = allCards.filter(({ id }) => id < 1000)

export const personalities = allCards.filter(({ id }) => id >= 1000)
